name: "Queue Job Checker"
description: "Checks if specific jobs are running in GitHub Actions workflows."
inputs:
  queue-jobs:
    description: "Comma-separated list of job names to check."
    required: true
  min-wait-time:
    description: "Minimum wait time in seconds."
    required: false
    default: 15
  max-wait-time:
    description: "Maximum wait time in seconds."
    required: false
    default: 30
  min-wait-before-start-time:
    description: "Minimum wait time before start in seconds."
    required: false
    default: 15
  max-wait-before-start-time:
    description: "Maximum wait time before start in seconds."
    required: false
    default: 30
  github-token:
    description: "GitHub token for authentication."
    required: false
    default: ${{ github.token }}
outputs:
  status:
    description: "The status of the queue check."
runs:
  using: "node20"
  main: "dist/index.js"
